### YamlMime:ManagedReference
items:
- uid: MacacaGames.GameSystem.ApplicationController.ApplicationState
  commentId: T:MacacaGames.GameSystem.ApplicationController.ApplicationState
  id: ApplicationController.ApplicationState
  parent: MacacaGames.GameSystem
  children:
  - MacacaGames.GameSystem.ApplicationController.ApplicationState.Gaming
  - MacacaGames.GameSystem.ApplicationController.ApplicationState.Lobby
  langs:
  - csharp
  - vb
  name: ApplicationController.ApplicationState
  nameWithType: ApplicationController.ApplicationState
  fullName: MacacaGames.GameSystem.ApplicationController.ApplicationState
  type: Enum
  source:
    remote:
      path: Runtime/ApplicationController.cs
      branch: master
      repo: git@github.com:MacacaGames/GameSystem.git
    id: ApplicationState
    path: ../Runtime/ApplicationController.cs
    startLine: 463
  assemblies:
  - Macaca.GameSystem
  namespace: MacacaGames.GameSystem
  summary: "\nAn enum to explain which state the application is.\n"
  example: []
  syntax:
    content: public enum ApplicationState
    content.vb: Public Enum ApplicationState
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: MacacaGames.GameSystem.ApplicationController.ApplicationState.Lobby
  commentId: F:MacacaGames.GameSystem.ApplicationController.ApplicationState.Lobby
  id: Lobby
  parent: MacacaGames.GameSystem.ApplicationController.ApplicationState
  langs:
  - csharp
  - vb
  name: Lobby
  nameWithType: ApplicationController.ApplicationState.Lobby
  fullName: MacacaGames.GameSystem.ApplicationController.ApplicationState.Lobby
  type: Field
  source:
    remote:
      path: Runtime/ApplicationController.cs
      branch: master
      repo: git@github.com:MacacaGames/GameSystem.git
    id: Lobby
    path: ../Runtime/ApplicationController.cs
    startLine: 468
  assemblies:
  - Macaca.GameSystem
  namespace: MacacaGames.GameSystem
  summary: "\nLobby is the homepage waiting for user to start the game\n"
  example: []
  syntax:
    content: Lobby = 0
    return:
      type: MacacaGames.GameSystem.ApplicationController.ApplicationState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: MacacaGames.GameSystem.ApplicationController.ApplicationState.Gaming
  commentId: F:MacacaGames.GameSystem.ApplicationController.ApplicationState.Gaming
  id: Gaming
  parent: MacacaGames.GameSystem.ApplicationController.ApplicationState
  langs:
  - csharp
  - vb
  name: Gaming
  nameWithType: ApplicationController.ApplicationState.Gaming
  fullName: MacacaGames.GameSystem.ApplicationController.ApplicationState.Gaming
  type: Field
  source:
    remote:
      path: Runtime/ApplicationController.cs
      branch: master
      repo: git@github.com:MacacaGames/GameSystem.git
    id: Gaming
    path: ../Runtime/ApplicationController.cs
    startLine: 474
  assemblies:
  - Macaca.GameSystem
  namespace: MacacaGames.GameSystem
  summary: "\nGaming, means user is in the GamePlay, equal to <xref href=\"MacacaGames.GameSystem.GamePlayController.isGaming\" data-throw-if-not-resolved=\"false\"></xref> == true\n, Use <xref href=\"MacacaGames.GameSystem.ApplicationController.GameState\" data-throw-if-not-resolved=\"false\"></xref> to know the detail state of the gaming. \n"
  example: []
  syntax:
    content: Gaming = 1
    return:
      type: MacacaGames.GameSystem.ApplicationController.ApplicationState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: MacacaGames.GameSystem
  commentId: N:MacacaGames.GameSystem
  name: MacacaGames.GameSystem
  nameWithType: MacacaGames.GameSystem
  fullName: MacacaGames.GameSystem
- uid: MacacaGames.GameSystem.ApplicationController.ApplicationState
  commentId: T:MacacaGames.GameSystem.ApplicationController.ApplicationState
  parent: MacacaGames.GameSystem
  name: ApplicationController.ApplicationState
  nameWithType: ApplicationController.ApplicationState
  fullName: MacacaGames.GameSystem.ApplicationController.ApplicationState
- uid: MacacaGames.GameSystem.GamePlayController.isGaming
  commentId: P:MacacaGames.GameSystem.GamePlayController.isGaming
  isExternal: true
- uid: MacacaGames.GameSystem.ApplicationController.GameState
  commentId: T:MacacaGames.GameSystem.ApplicationController.GameState
  parent: MacacaGames.GameSystem
  name: ApplicationController.GameState
  nameWithType: ApplicationController.GameState
  fullName: MacacaGames.GameSystem.ApplicationController.GameState
